version: "3.3"

services:
  backend:
    container_name: node
    build: ./server
#    volumes:
#      - .:/srv/app/node-server
    environment:
      - NODE_ENV=production
    expose:
      - "9999"
    ports:
      - "8081:9999"
    working_dir: /srv/app/node-server
    command: yarn start

#  frontend:
#    container_name: react
#    build: ./client
#    ports:
#      - "3000:3000"
#    links:
#      - backend
#    command: yarn start

